### ISSUE TITLE
Ветка main

### ISSUE THREAD

**Issue by Oktopus90** [astronautsus/Backwood#2]
Результат не может быть автоматически зачтен и проверен, тк основная ветка переименована. 
Для корректной работы верните имя основной ветки main

**Comment by Oktopus90** [comment]
Вот ссылка на инструкцию
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch

**Comment by astronautsus** [comment]
fixed))
